server:
  port: 8072
spring:
  application:
    name: service-member
#  datasource:
#    name: orderingsystem
#    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka/
  instance:
    prefer-ip-address: true
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.southwind.entity